### ISSUE TITLE
When opening bot.py the application does not open

### ISSUE THREAD

**Issue by ShadowMethods** [mrgrupprr/Discord-baker#11]
Hi i followed your guide and did every step but i feel like im missing some steps because after i followed all the steps and opened application.py & bot.py they both did not open and just closed. Also your discord username is wrong can you leave me your discord tag so we can chat on discord?

**Comment by mrgrupprr** [comment]
I can tell you why, you need to go into the directory and go into cmd / terminal navigate into the directory and than run it.
