### ISSUE TITLE
Bad Request for url: https://discord.com/api/v9/oauth2/token

### ISSUE THREAD

**Issue by svn-josh** [mrgrupprr/Discord-baker#12]
![image](https://user-images.githubusercontent.com/39739909/191562844-60a3f318-e1d8-4afe-b291-2ea574bad0a1.png)

![image](https://user-images.githubusercontent.com/39739909/191562907-ef2a8eac-ddd9-45d1-9ed0-577023fdee40.png)

**Comment by svn-josh** [comment]
after clicking on "click me" in discord and accepting the auth. You get redirected to this page and the console throws a error.

(btw. in bot.py there is a typo in line 40. it says "uri" but should be "url")

**Comment by mrgrupprr** [comment]
I tested the setup for me it works.

**Comment by svn-josh** [comment]
could you send me your discord? i cant figure out why it doesnt work...
