### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by svn-josh** [mrgrupprr/Discord-baker#13]
Hello, some things are not working properlly. for you they my work but not for all.
like bot.py has some errors, typo in line 40, then in the imports, (from dc import options, this module does not come with the pycord version you wrote in requirements)

also i think you changed your discord name. the one you wrote does not work anymore. could you update it?

**Comment by mrgrupprr** [comment]
I got banned sadly. Add me haze#8235

**Comment by svn-josh** [comment]
thanks, send you a request
