### ISSUE TITLE
request

### ISSUE THREAD

**Issue by Anydex** [mrgrupprr/Discord-baker#7]
Can you add support for multiple discord bots to connect to the same server/api and verify members in different guilds or have support for 1 bot to be able to verify in multiple servers

**Comment by mrgrupprr** [comment]
Going to add this to the to-do list, this is going to be added next

**Comment by Anydex** [comment]
Thank you

**Comment by mrgrupprr** [comment]
Multiple guild supported, but the verified role name must be the same.
